const AGW_ERROR_CODES = Object.freeze({
    INVALID_REQUEST: 'AGW_INVALID_REQUEST',
    UNAUTHORIZED: 'AGW_UNAUTHORIZED',
    VALIDATION_ERROR: 'AGW_VALIDATION_ERROR',
    FORBIDDEN: 'AGW_FORBIDDEN',
    NOT_FOUND: 'AGW_NOT_FOUND',
    TIMEOUT: 'AGW_TIMEOUT',
    INTERNAL_ERROR: 'AGW_INTERNAL_ERROR'
});

const OPENCLAW_ERROR_CODES = Object.freeze({
    INVALID_REQUEST: 'OCW_INVALID_REQUEST',
    INTERNAL_ERROR: 'OCW_INTERNAL_ERROR',
    RAG_INVALID_QUERY: 'OCW_RAG_INVALID_QUERY',
    RAG_TARGET_NOT_FOUND: 'OCW_RAG_TARGET_NOT_FOUND',
    RAG_TARGET_FORBIDDEN: 'OCW_RAG_TARGET_FORBIDDEN',
    RAG_SEARCH_ERROR: 'OCW_RAG_SEARCH_ERROR',
    RAG_CONTEXT_ERROR: 'OCW_RAG_CONTEXT_ERROR',
    MEMORY_INVALID_PAYLOAD: 'OCW_MEMORY_INVALID_PAYLOAD',
    MEMORY_TARGET_FORBIDDEN: 'OCW_MEMORY_TARGET_FORBIDDEN',
    MEMORY_WRITE_ERROR: 'OCW_MEMORY_WRITE_ERROR',
    TOOL_NOT_FOUND: 'OCW_TOOL_NOT_FOUND',
    TOOL_FORBIDDEN: 'OCW_TOOL_FORBIDDEN',
    TOOL_APPROVAL_REQUIRED: 'OCW_TOOL_APPROVAL_REQUIRED',
    TOOL_INVALID_ARGS: 'OCW_TOOL_INVALID_ARGS',
    TOOL_TIMEOUT: 'OCW_TOOL_TIMEOUT',
    TOOL_EXECUTION_ERROR: 'OCW_TOOL_EXECUTION_ERROR'
});

const OPENCLAW_TO_AGENT_GATEWAY_CODE = Object.freeze({
    [OPENCLAW_ERROR_CODES.INVALID_REQUEST]: AGW_ERROR_CODES.INVALID_REQUEST,
    [OPENCLAW_ERROR_CODES.INTERNAL_ERROR]: AGW_ERROR_CODES.INTERNAL_ERROR,
    [OPENCLAW_ERROR_CODES.RAG_INVALID_QUERY]: AGW_ERROR_CODES.VALIDATION_ERROR,
    [OPENCLAW_ERROR_CODES.RAG_TARGET_NOT_FOUND]: AGW_ERROR_CODES.NOT_FOUND,
    [OPENCLAW_ERROR_CODES.RAG_TARGET_FORBIDDEN]: AGW_ERROR_CODES.FORBIDDEN,
    [OPENCLAW_ERROR_CODES.RAG_SEARCH_ERROR]: AGW_ERROR_CODES.INTERNAL_ERROR,
    [OPENCLAW_ERROR_CODES.RAG_CONTEXT_ERROR]: AGW_ERROR_CODES.INTERNAL_ERROR,
    [OPENCLAW_ERROR_CODES.MEMORY_INVALID_PAYLOAD]: AGW_ERROR_CODES.VALIDATION_ERROR,
    [OPENCLAW_ERROR_CODES.MEMORY_TARGET_FORBIDDEN]: AGW_ERROR_CODES.FORBIDDEN,
    [OPENCLAW_ERROR_CODES.MEMORY_WRITE_ERROR]: AGW_ERROR_CODES.INTERNAL_ERROR,
    [OPENCLAW_ERROR_CODES.TOOL_NOT_FOUND]: AGW_ERROR_CODES.NOT_FOUND,
    [OPENCLAW_ERROR_CODES.TOOL_FORBIDDEN]: AGW_ERROR_CODES.FORBIDDEN,
    [OPENCLAW_ERROR_CODES.TOOL_APPROVAL_REQUIRED]: AGW_ERROR_CODES.FORBIDDEN,
    [OPENCLAW_ERROR_CODES.TOOL_INVALID_ARGS]: AGW_ERROR_CODES.VALIDATION_ERROR,
    [OPENCLAW_ERROR_CODES.TOOL_TIMEOUT]: AGW_ERROR_CODES.TIMEOUT,
    [OPENCLAW_ERROR_CODES.TOOL_EXECUTION_ERROR]: AGW_ERROR_CODES.INTERNAL_ERROR
});

module.exports = {
    AGW_ERROR_CODES,
    OPENCLAW_ERROR_CODES,
    OPENCLAW_TO_AGENT_GATEWAY_CODE
};
